### ISSUE TITLE
I love this! but...

### ISSUE THREAD

**Issue by fiveseven808** [zulubo/SpecularProbes#2]
So, I love this! But I feel like this is doing the same thing when the unity editor switches to an android environment?  It converts my realtime directional light to basically what your method is doing? 

In either case, my issue is that walls do not seem to occlude the reflection from the emissive source. Like if I have a plane, and the light is  supposed to be occluded by a wall on the plane, the plane will still reflect the specular highlight of the light source as if the wall wasn't there. 

Is this something that we can solve

**Comment by zulubo** [comment]
I don't develop for android so I can't speak on that.

This method of rendering reflections does not support shadows, and there's no way to solve this. You can work around it by placing reflection probes more carefully, i.e. one probe in the area that can see the light and another probe in the area that is occluded.
